spring:
  config:
    import: "file:env.properties"
  main:
    banner-mode: off
  application:
    name: authorize_net_pay_demo
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql

server:
  port: 1915

authorizenet:
  apiLoginId: ${API_LOGIN_ID}
  transactionKey: ${TRANSACTION_KEY}